### ISSUE TITLE
Android MainFest Issue

### ISSUE THREAD

**Issue by itRookieMonster** [Awent/PhotoPick-Master#1]
大牛好，我在引用这个框架的时候出现一个问题，就是我的application的label被你框架的label覆盖了 我在我的application里面加了一句tools:replace="label" 还是无法修改 这个有什么好的建议吗？我的uses-sdk  min=15 target=17

**Comment by Awent** [comment]
已修复，请更新gradle到1.03 ： `dependencies {
	        compile 'com.github.Awent:PhotoPick-Master:v1.03'
	}`

**Comment by itRookieMonster** [comment]
Thank you very much ,你好 当我更新到1.03以后提示 recyclerview-v7:25.1.1 和appCompat-v7:25.1.1 not found ，而我的项目的BuildVersion 25.0.2 ，compile是25 如果不升级的话就报错了 ，这个版本问题是否能再改善一下呢？万分感谢您的耐心回复

**Comment by Awent** [comment]
请到Android SDK Manager->Extras->Android support Repository进行更新。最新版本的recycleview可能优化得更好，为什么不更新呢。

**Comment by itRookieMonster** [comment]
好的 谢谢
