### ISSUE TITLE
查看网络长图，大图时，放大缩小动画很卡，拖动很迟钝

### ISSUE THREAD

**Issue by BaiYuMoO** [Awent/PhotoPick-Master#11]

**Comment by Awent** [comment]
可以把你的原图放上来，我想进行调试下？

**Comment by Awent** [comment]
@BaiYuMoO 可以把你的原图放上来，我想进行调试下？

**Comment by BaiYuMoO** [comment]
![d13bde6a9dec4f67ba819e0d57f1dee9](https://user-images.githubusercontent.com/39898537/61259085-3449aa80-a7ab-11e9-90bb-0359971e3d15.jpg)
![3257d1596dce4c3ba6df5925613bf0ac](https://user-images.githubusercontent.com/39898537/61259086-34e24100-a7ab-11e9-9643-2ad2f50dee6f.jpg)
![96c5a0d4ab2244938e819f2c86e97711](https://user-images.githubusercontent.com/39898537/61259087-34e24100-a7ab-11e9-9c6c-6b2d8ffa43a1.jpg)

**Comment by BaiYuMoO** [comment]
稍微大一点的图放大之后拖动都很卡，更新控件版本也没用

**Comment by Awent** [comment]
@BaiYuMoO 我拿你的图试了，是没什么问题的，我的手机是荣耀10，我测试了网络长图最大的5M，本地长图9M，放大缩小拖动都没卡顿现象，很流畅。不知道你说的稍微大一点的图是多大呢，我找不到超过10M的图来进行测试 ^_^!

**Comment by BaiYuMoO** [comment]
@Awent 我写的demo放上去写没有问题，放在要用的app中就变得卡顿，不知道是否配置有问题或是和其它插件有冲突，总之先谢谢大佬了。

**Comment by BaiYuMoO** [comment]
找到原因了，，Manifest下的application标签我加了个android:hardwareAccelerated="false"属性，删掉就好了，坑死了

**Comment by Awent** [comment]
@BaiYuMoO 没问题就好，哈哈，还有什么问题再提交哦
