### ISSUE TITLE
保存图片失败

### ISSUE THREAD

**Issue by XD-Z** [Awent/PhotoPick-Master#13]
点击保存图片失败，（只有一个toast提示）设置和不设置setSaveImageLocalPath（这里是你想保存的图片地址）这个属性，都不行，想问下怎么解决

**Comment by Awent** [comment]
android 10 需要在自己的**AndroidManifest.xml**的  `application`节点添加适配代码：`android:requestLegacyExternalStorage="true"`，即可保存成功

例子：
```
<application
        android:name=".App"
        android:requestLegacyExternalStorage="true"
        android:theme="@style/AppTheme">
```
