### ISSUE TITLE
导入项目之后，build出现java.util.concurrent.ExecutionException: com.android.tools.aapt2.Aapt2Exception: AAPT2 error: check logs for details

### ISSUE THREAD

**Issue by MrZhouXiang** [Awent/PhotoPick-Master#2]
![image](https://user-images.githubusercontent.com/9959694/33428294-34c04e86-d603-11e7-8b4f-9ff0a0307be2.png)
    compile 'com.github.Awent:PhotoPick-Master:v1.092'
导入项目之后，build出现如上错误，不知道怎么解决

**Comment by Awent** [comment]
试下这种解决方案：[Android Studio 3.0 RC 2](https://stackoverflow.com/questions/46910532/android-studio-3-0-rc-2)。在你的**gradle.properties**添加：**android.enableAapt2=false**

**Comment by gongzhiq** [comment]
resource android:style/TextAppearance.Material.Widget.Button.Inverse not found.	
resource android:style/Widget.Material.Button.Colored not found.	
failed linking references.
