### ISSUE TITLE
部分机型选择图片进行裁剪时，如果图片来自拍摄或相册图片时，图片处于翻转状态，无法得到预期效果。

### ISSUE THREAD

**Issue by hito-zhang** [Awent/PhotoPick-Master#7]
我的处理方法是在获取图片路径进行裁剪时，加入是否旋转的判断，由于是在源码改的，希望作者可以加入这一步。
![image](https://user-images.githubusercontent.com/11548042/51161919-3d76bf00-18cf-11e9-8de5-a05f8ead4177.png)

**Comment by hito-zhang** [comment]
/**
     * 读取照片旋转角度
     *
     * @param path 照片路径
     * @return 角度
     */
    public static int readPictureDegree(String path) {
        int degree = 0;
        try {
            ExifInterface exifInterface = new ExifInterface(path);
            int orientation = exifInterface.getAttributeInt(ExifInterface.TAG_ORIENTATION, ExifInterface.ORIENTATION_NORMAL);
//            Log.e(TAG, "readPictureDegree: orientation-------->"+orientation);
            switch (orientation) {
                case ExifInterface.ORIENTATION_ROTATE_90:
                    degree = 90;
                    break;
                case ExifInterface.ORIENTATION_ROTATE_180:
                    degree = 180;
                    break;
                case ExifInterface.ORIENTATION_ROTATE_270:
                    degree = 270;
                    break;
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
//        Log.e(TAG, "readPictureDegree: degree-origin------->"+degree);
        return degree;
    }
 /**
     * 旋转图片
     * @param angle 被旋转角度
     * @param bitmap 图片对象
     * @return 旋转后的图片
     */
    public static Bitmap rotaingImageView(int angle, Bitmap bitmap) {
        Bitmap returnBm = null;
        // 根据旋转角度，生成旋转矩阵
        Matrix matrix = new Matrix();
        matrix.postRotate(angle);
        try {
            // 将原始图片按照旋转矩阵进行旋转，并得到新的图片
            returnBm = Bitmap.createBitmap(bitmap, 0, 0, bitmap.getWidth(), bitmap.getHeight(), matrix, true);
        } catch (OutOfMemoryError e) {
        }
        if (returnBm == null) {
            returnBm = bitmap;
        }
        if (bitmap != returnBm) {
            bitmap.recycle();
        }
        return returnBm;
    }

**Comment by Awent** [comment]
@taoczZYC 加啦，你也可以pull request，我会尽快通过的
